from __future__ import annotations
from typing import Any
from pydantic import BaseModel, Field


class TopicCandidate(BaseModel):
    """Represents a potential debate topic."""
    title: str
    description: str
    category: str  # e.g., "technology", "economics", "society"
    score: float = Field(ge=0.0, le=1.0)
    source: str  # e.g., "google_trends", "news_api"
    keywords: list[str] = Field(default_factory=list)


class AgentProfile(BaseModel):
    """Represents one of the two debating AI agents."""
    id: str
    name: str
    position: str  # "賛成" | "反対" | custom stance


class ScriptSegment(BaseModel):
    """A single utterance in the debate."""
    speaker: str  # agent id
    text: str
    emotion: int = Field(ge=0, le=100, description="Emotional intensity 0-100")
    interrupt_at: int | None = Field(
        default=None, description="Timestamp in ms where interruption occurs"
    )
    data_visual: dict[str, Any] | None = Field(
        default=None, description="Optional chart/visualization data"
    )


class CTAConfig(BaseModel):
    """Call-to-action configuration for LINE funnel."""
    text: str
    line_url: str


class DebateScript(BaseModel):
    """Full debate script generated by Gemini."""
    title: str
    topic: str
    agents: list[AgentProfile] = Field(min_length=2, max_length=2)
    segments: list[ScriptSegment] = Field(min_length=1)
    cliffhanger: str = Field(description="Unresolved dilemma to end the video")
    cta: CTAConfig
    metadata: dict[str, Any] = Field(default_factory=dict)


class AudioSegment(BaseModel):
    """Audio file info for a single script segment."""
    segment_index: int
    speaker: str
    file_path: str
    start_ms: int
    duration_ms: int
    emotion: int


class AudioManifest(BaseModel):
    """Manifest of all generated audio segments."""
    script_title: str
    total_duration_ms: int
    segments: list[AudioSegment]


class ReviewIssue(BaseModel):
    """A single issue found during script review."""
    issue_type: str  # "fact_error" | "policy_violation" | "quality"
    severity: str    # "error" | "warning"
    segment_index: int | None
    description: str
    suggestion: str | None = None


class ReviewResult(BaseModel):
    """Result from the script reviewer."""
    passed: bool
    issues: list[ReviewIssue] = Field(default_factory=list)
    corrected_script: DebateScript | None = None
    review_count: int = 0
